name: CI/CD Pipeline

on:
  push:
    branches:
      - production-Live  # This triggers the script every time you push to 'main' hiiiiiiii

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/solestyle-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/solestyle-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Clear disk space (The Janitor)
            sudo docker system prune -af --volumes

            # 2. Stop and remove the old container
            sudo docker stop solestyle-app || true
            sudo docker rm solestyle-app || true

            # 3. Pull the latest image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/solestyle-app:latest
            
            # 4. Run the new container
            sudo docker run -d \
              --name solestyle-app \
              -p 5000:5000 \
              --env-file /home/ubuntu/.env \
              ${{ secrets.DOCKER_USERNAME }}/solestyle-app:latest

            # 5. Final Nginx Refresh
            sudo systemctl restart nginx